### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Agent-No-7** [Leanny/leanny.github.io#127]
Is there any reports/feedback on editing hero mode data? Is that an instant red flag like level editing or is it relatively safe to make changes (like chunks and tickets)? 

Second question:  have there been any reports of instant bans with edits of any type with the recent splatoon update?

Third:
Is there anywhere we can check or read up on before bothering you with questions that have probably been asked many times before?

Thank you for your patience and I await your reply.

**Comment by Leanny** [comment]
First: in theory it's safe, because you can just do it offline (assuming you did it 'the legal way' and not finish bosses without playing the regular levels). Practically I did not receive any reports for possible bans yet.
Second: I received a ban report 4 days ago for editing chunks + add all missing gear. 
Third: not really, the best you can do is to check the (closed) issues. 

If you want to minimize your ban risk, do the following:
1. Disable telemetry sending (EU accounts can go to https://accounts.nintendo.com/setting and disabling sharing usage information with Nintendo. Blocking "receive-lp1.dg.srv.nintendo.net" in your router settings should do the same for non EU users.)
2. Disable sending data in your switch settings + disable auto updates
3. Make sure you are offline when in cfw
4. Boot the game after editing it, change your gear or whatever to make the game save before going online again. 
5. Don't go online with cfw at all

These steps should minimize the risk, but you are never 100% safe nowadays
