### ISSUE TITLE
What is the future of splathex?

### ISSUE THREAD

**Issue by hottoast16** [Leanny/leanny.github.io#142]
Title. Are you planning on updating splathex in the near future? If not would you mind providing advice on how someone else might continue the project? Thanks a lot Leanny.

**Comment by Leanny** [comment]
Sorry for the late response. Due to upgraded anti cheat meachanism in nearly every update we decided to stop supporting splathex.
I do not know if anyone wants to make a similar editor or anything, but save file decryptors are open source and savegame structure is well documented in public wikis, so it shouldn't be hard for others to start their own editor
